import { Service } from '../models/service.model';

export const SERVICES: Service[] = [
  {
    id: 1,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 2,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 3,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 4,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 5,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 6,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 7,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 8,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 9,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 10,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 11,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 12,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 13,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 14,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 15,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 16,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 17,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 18,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 19,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 20,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 21,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 22,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 23,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 24,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 25,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 26,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 27,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 28,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 29,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 30,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 31,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 32,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 33,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 34,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 35,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 36,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
  {
    id: 37,
    serviceName: 'Property Ownership',
    code: 'P-Q2',
    type: 'Service Type',
    status: 'Inactive',
  },
  {
    id: 38,
    serviceName: 'Property Transfer',
    code: 'P-T01',
    type: 'Service Type',
    status: 'Active',
  },
];
